export interface StockEntry {
  name: string;
  ticker: string;
  sector: string;
}

export const NSE_STOCKS: StockEntry[] = [
  // Nifty 50 & Large Caps
  { name: "Reliance Industries", ticker: "RELIANCE.NS", sector: "Oil & Gas" },
  { name: "Tata Consultancy Services", ticker: "TCS.NS", sector: "IT" },
  { name: "HDFC Bank", ticker: "HDFCBANK.NS", sector: "Banking" },
  { name: "Infosys", ticker: "INFY.NS", sector: "IT" },
  { name: "ICICI Bank", ticker: "ICICIBANK.NS", sector: "Banking" },
  { name: "Hindustan Unilever", ticker: "HINDUNILVR.NS", sector: "FMCG" },
  { name: "ITC", ticker: "ITC.NS", sector: "FMCG" },
  { name: "State Bank of India", ticker: "SBIN.NS", sector: "Banking" },
  { name: "Bharti Airtel", ticker: "BHARTIARTL.NS", sector: "Telecom" },
  { name: "Kotak Mahindra Bank", ticker: "KOTAKBANK.NS", sector: "Banking" },
  { name: "Larsen & Toubro", ticker: "LT.NS", sector: "Infrastructure" },
  { name: "Axis Bank", ticker: "AXISBANK.NS", sector: "Banking" },
  { name: "Asian Paints", ticker: "ASIANPAINT.NS", sector: "Paints" },
  { name: "Maruti Suzuki", ticker: "MARUTI.NS", sector: "Auto" },
  { name: "Titan Company", ticker: "TITAN.NS", sector: "Consumer" },
  { name: "Bajaj Finance", ticker: "BAJFINANCE.NS", sector: "NBFC" },
  { name: "Sun Pharma", ticker: "SUNPHARMA.NS", sector: "Pharma" },
  { name: "Wipro", ticker: "WIPRO.NS", sector: "IT" },
  { name: "HCL Technologies", ticker: "HCLTECH.NS", sector: "IT" },
  { name: "Tata Motors", ticker: "TATAMOTORS.NS", sector: "Auto" },
  { name: "UltraTech Cement", ticker: "ULTRACEMCO.NS", sector: "Cement" },
  { name: "Nestle India", ticker: "NESTLEIND.NS", sector: "FMCG" },
  { name: "Power Grid Corp", ticker: "POWERGRID.NS", sector: "Power" },
  { name: "NTPC", ticker: "NTPC.NS", sector: "Power" },
  { name: "Mahindra & Mahindra", ticker: "M&M.NS", sector: "Auto" },
  { name: "Bajaj Finserv", ticker: "BAJAJFINSV.NS", sector: "NBFC" },
  { name: "Tech Mahindra", ticker: "TECHM.NS", sector: "IT" },
  { name: "Tata Steel", ticker: "TATASTEEL.NS", sector: "Metals" },
  { name: "IndusInd Bank", ticker: "INDUSINDBK.NS", sector: "Banking" },
  { name: "Adani Enterprises", ticker: "ADANIENT.NS", sector: "Conglomerate" },
  { name: "Adani Ports", ticker: "ADANIPORTS.NS", sector: "Ports" },
  { name: "Adani Green Energy", ticker: "ADANIGREEN.NS", sector: "Renewable Energy" },
  { name: "Adani Power", ticker: "ADANIPOWER.NS", sector: "Power" },
  { name: "Grasim Industries", ticker: "GRASIM.NS", sector: "Cement" },
  { name: "Cipla", ticker: "CIPLA.NS", sector: "Pharma" },
  { name: "Dr Reddy's Labs", ticker: "DRREDDY.NS", sector: "Pharma" },
  { name: "Coal India", ticker: "COALINDIA.NS", sector: "Mining" },
  { name: "Eicher Motors", ticker: "EICHERMOT.NS", sector: "Auto" },
  { name: "Britannia Industries", ticker: "BRITANNIA.NS", sector: "FMCG" },
  { name: "Divi's Labs", ticker: "DIVISLAB.NS", sector: "Pharma" },
  { name: "Bajaj Auto", ticker: "BAJAJ-AUTO.NS", sector: "Auto" },
  { name: "Hero MotoCorp", ticker: "HEROMOTOCO.NS", sector: "Auto" },
  { name: "JSW Steel", ticker: "JSWSTEEL.NS", sector: "Metals" },
  { name: "SBI Life Insurance", ticker: "SBILIFE.NS", sector: "Insurance" },
  { name: "HDFC Life Insurance", ticker: "HDFCLIFE.NS", sector: "Insurance" },
  { name: "Apollo Hospitals", ticker: "APOLLOHOSP.NS", sector: "Healthcare" },
  { name: "Tata Consumer Products", ticker: "TATACONSUM.NS", sector: "FMCG" },
  { name: "Hindalco Industries", ticker: "HINDALCO.NS", sector: "Metals" },
  { name: "BPCL", ticker: "BPCL.NS", sector: "Oil & Gas" },
  { name: "Oil & Natural Gas Corp", ticker: "ONGC.NS", sector: "Oil & Gas" },

  // Mid & Small Caps - Popular
  { name: "Zomato", ticker: "ZOMATO.NS", sector: "Tech" },
  { name: "Paytm (One97)", ticker: "PAYTM.NS", sector: "Fintech" },
  { name: "Nykaa (FSN E-Commerce)", ticker: "NYKAA.NS", sector: "E-Commerce" },
  { name: "PB Fintech (Policybazaar)", ticker: "POLICYBZR.NS", sector: "Fintech" },
  { name: "Delhivery", ticker: "DELHIVERY.NS", sector: "Logistics" },
  { name: "Vedanta", ticker: "VEDL.NS", sector: "Mining" },
  { name: "Tata Power", ticker: "TATAPOWER.NS", sector: "Power" },
  { name: "Tata Elxsi", ticker: "TATAELXSI.NS", sector: "IT" },
  { name: "Pidilite Industries", ticker: "PIDILITIND.NS", sector: "Chemicals" },
  { name: "Havells India", ticker: "HAVELLS.NS", sector: "Electricals" },
  { name: "Godrej Consumer", ticker: "GODREJCP.NS", sector: "FMCG" },
  { name: "Dabur India", ticker: "DABUR.NS", sector: "FMCG" },
  { name: "Colgate Palmolive", ticker: "COLPAL.NS", sector: "FMCG" },
  { name: "Marico", ticker: "MARICO.NS", sector: "FMCG" },
  { name: "Berger Paints", ticker: "BERGEPAINT.NS", sector: "Paints" },
  { name: "Siemens", ticker: "SIEMENS.NS", sector: "Capital Goods" },
  { name: "ABB India", ticker: "ABB.NS", sector: "Capital Goods" },
  { name: "Bharat Electronics", ticker: "BEL.NS", sector: "Defense" },
  { name: "HAL (Hindustan Aeronautics)", ticker: "HAL.NS", sector: "Defense" },
  { name: "Indian Railway Catering", ticker: "IRCTC.NS", sector: "Travel" },
  { name: "Dixon Technologies", ticker: "DIXON.NS", sector: "Electronics" },
  { name: "Varun Beverages", ticker: "VBL.NS", sector: "Beverages" },
  { name: "Trent", ticker: "TRENT.NS", sector: "Retail" },
  { name: "Avenue Supermarts (DMart)", ticker: "DMART.NS", sector: "Retail" },
  { name: "Page Industries", ticker: "PAGEIND.NS", sector: "Textiles" },
  { name: "Muthoot Finance", ticker: "MUTHOOTFIN.NS", sector: "NBFC" },
  { name: "Cholamandalam Investment", ticker: "CHOLAFIN.NS", sector: "NBFC" },
  { name: "Shriram Finance", ticker: "SHRIRAMFIN.NS", sector: "NBFC" },
  { name: "ICICI Prudential Life", ticker: "ICICIPRULI.NS", sector: "Insurance" },
  { name: "Max Healthcare", ticker: "MAXHEALTH.NS", sector: "Healthcare" },
  { name: "Fortis Healthcare", ticker: "FORTIS.NS", sector: "Healthcare" },
  { name: "Laurus Labs", ticker: "LAURUSLABS.NS", sector: "Pharma" },
  { name: "Biocon", ticker: "BIOCON.NS", sector: "Pharma" },
  { name: "Aurobindo Pharma", ticker: "AUROPHARMA.NS", sector: "Pharma" },
  { name: "Torrent Pharma", ticker: "TORNTPHARM.NS", sector: "Pharma" },
  { name: "Indian Oil Corp", ticker: "IOC.NS", sector: "Oil & Gas" },
  { name: "Hindustan Petroleum", ticker: "HINDPETRO.NS", sector: "Oil & Gas" },
  { name: "Bharat Petroleum", ticker: "BPCL.NS", sector: "Oil & Gas" },
  { name: "JSW Energy", ticker: "JSWENERGY.NS", sector: "Power" },
  { name: "Adani Total Gas", ticker: "ATGL.NS", sector: "Gas" },
  { name: "Indus Towers", ticker: "INDUSTOWER.NS", sector: "Telecom" },
  { name: "Vodafone Idea", ticker: "IDEA.NS", sector: "Telecom" },
  { name: "Bank of Baroda", ticker: "BANKBARODA.NS", sector: "Banking" },
  { name: "Punjab National Bank", ticker: "PNB.NS", sector: "Banking" },
  { name: "Canara Bank", ticker: "CANBK.NS", sector: "Banking" },
  { name: "Federal Bank", ticker: "FEDERALBNK.NS", sector: "Banking" },
  { name: "Bandhan Bank", ticker: "BANDHANBNK.NS", sector: "Banking" },
  { name: "IDFC First Bank", ticker: "IDFCFIRSTB.NS", sector: "Banking" },
  { name: "L&T Technology Services", ticker: "LTTS.NS", sector: "IT" },
  { name: "Mphasis", ticker: "MPHASIS.NS", sector: "IT" },
  { name: "Persistent Systems", ticker: "PERSISTENT.NS", sector: "IT" },
  { name: "Coforge", ticker: "COFORGE.NS", sector: "IT" },
  { name: "LTIMindtree", ticker: "LTIM.NS", sector: "IT" },
  { name: "Polycab India", ticker: "POLYCAB.NS", sector: "Electricals" },
  { name: "KEI Industries", ticker: "KEI.NS", sector: "Electricals" },
  { name: "Crompton Greaves", ticker: "CROMPTON.NS", sector: "Electricals" },
  { name: "Voltas", ticker: "VOLTAS.NS", sector: "Consumer Durables" },
  { name: "Whirlpool India", ticker: "WHIRLPOOL.NS", sector: "Consumer Durables" },
  { name: "Blue Star", ticker: "BLUESTARCO.NS", sector: "Consumer Durables" },
  { name: "Ambuja Cements", ticker: "AMBUJACEM.NS", sector: "Cement" },
  { name: "Shree Cement", ticker: "SHREECEM.NS", sector: "Cement" },
  { name: "ACC", ticker: "ACC.NS", sector: "Cement" },
  { name: "Dalmia Bharat", ticker: "DALBHARAT.NS", sector: "Cement" },
  { name: "PI Industries", ticker: "PIIND.NS", sector: "Chemicals" },
  { name: "SRF", ticker: "SRF.NS", sector: "Chemicals" },
  { name: "Deepak Nitrite", ticker: "DEEPAKNTR.NS", sector: "Chemicals" },
  { name: "Atul", ticker: "ATUL.NS", sector: "Chemicals" },
  { name: "Container Corp", ticker: "CONCOR.NS", sector: "Logistics" },
  { name: "InterGlobe Aviation (IndiGo)", ticker: "INDIGO.NS", sector: "Aviation" },
  { name: "Jubilant FoodWorks", ticker: "JUBLFOOD.NS", sector: "QSR" },
  { name: "Info Edge (Naukri)", ticker: "NAUKRI.NS", sector: "Tech" },
  { name: "MakeMyTrip", ticker: "MMYT.NS", sector: "Travel" },
  { name: "Mazagon Dock", ticker: "MAZDOCK.NS", sector: "Defense" },
  { name: "Cochin Shipyard", ticker: "COCHINSHIP.NS", sector: "Defense" },
  { name: "Solar Industries", ticker: "SOLARINDS.NS", sector: "Defense" },
  { name: "Data Patterns", ticker: "DATAPATTNS.NS", sector: "Defense" },
  { name: "IRFC", ticker: "IRFC.NS", sector: "Railways" },
  { name: "RVNL", ticker: "RVNL.NS", sector: "Railways" },
  { name: "Suzlon Energy", ticker: "SUZLON.NS", sector: "Renewable Energy" },
  { name: "NHPC", ticker: "NHPC.NS", sector: "Power" },
  { name: "Tata Technologies", ticker: "TATATECH.NS", sector: "IT" },
  { name: "Jio Financial Services", ticker: "JIOFIN.NS", sector: "NBFC" },
  { name: "LIC (Life Insurance Corp)", ticker: "LICI.NS", sector: "Insurance" },

  // Nifty Next 50 & Additional Large/Mid Caps
  { name: "DLF", ticker: "DLF.NS", sector: "Real Estate" },
  { name: "Godrej Properties", ticker: "GODREJPROP.NS", sector: "Real Estate" },
  { name: "Oberoi Realty", ticker: "OBEROIRLTY.NS", sector: "Real Estate" },
  { name: "Prestige Estates", ticker: "PRESTIGE.NS", sector: "Real Estate" },
  { name: "Bharti Hexacom", ticker: "BHARTIHEXA.NS", sector: "Telecom" },
  { name: "Mankind Pharma", ticker: "MANKIND.NS", sector: "Pharma" },
  { name: "Lupin", ticker: "LUPIN.NS", sector: "Pharma" },
  { name: "Alkem Laboratories", ticker: "ALKEM.NS", sector: "Pharma" },
  { name: "Glenmark Pharma", ticker: "GLENMARK.NS", sector: "Pharma" },
  { name: "IPCA Laboratories", ticker: "IPCALAB.NS", sector: "Pharma" },
  { name: "Natco Pharma", ticker: "NATCOPHARM.NS", sector: "Pharma" },
  { name: "Samvardhana Motherson", ticker: "MOTHERSON.NS", sector: "Auto" },
  { name: "Ashok Leyland", ticker: "ASHOKLEY.NS", sector: "Auto" },
  { name: "Bharat Forge", ticker: "BHARATFORG.NS", sector: "Auto" },
  { name: "TVS Motor", ticker: "TVSMOTOR.NS", sector: "Auto" },
  { name: "Tube Investments", ticker: "TIINDIA.NS", sector: "Auto" },
  { name: "Sona BLW Precision", ticker: "SONACOMS.NS", sector: "Auto" },
  { name: "Bosch", ticker: "BOSCHLTD.NS", sector: "Auto" },
  { name: "MRF", ticker: "MRF.NS", sector: "Auto" },
  { name: "Apollo Tyres", ticker: "APOLLOTYRE.NS", sector: "Auto" },
  { name: "CEAT", ticker: "CEATLTD.NS", sector: "Auto" },
  { name: "Indian Energy Exchange", ticker: "IEX.NS", sector: "Power" },
  { name: "Power Finance Corp", ticker: "PFC.NS", sector: "Power" },
  { name: "REC Ltd", ticker: "RECLTD.NS", sector: "Power" },
  { name: "Torrent Power", ticker: "TORNTPOWER.NS", sector: "Power" },
  { name: "CESC", ticker: "CESC.NS", sector: "Power" },
  { name: "Adani Energy Solutions", ticker: "ADANIENSOL.NS", sector: "Power" },
  { name: "GAIL India", ticker: "GAIL.NS", sector: "Oil & Gas" },
  { name: "Petronet LNG", ticker: "PETRONET.NS", sector: "Oil & Gas" },
  { name: "Gujarat Gas", ticker: "GUJGASLTD.NS", sector: "Oil & Gas" },
  { name: "Indraprastha Gas", ticker: "IGL.NS", sector: "Oil & Gas" },
  { name: "Mahanagar Gas", ticker: "MGL.NS", sector: "Oil & Gas" },
  { name: "Navin Fluorine", ticker: "NAVINFLUOR.NS", sector: "Chemicals" },
  { name: "Clean Science & Technology", ticker: "CLEAN.NS", sector: "Chemicals" },
  { name: "Aarti Industries", ticker: "AARTIIND.NS", sector: "Chemicals" },
  { name: "UPL", ticker: "UPL.NS", sector: "Chemicals" },
  { name: "Coromandel International", ticker: "COROMANDEL.NS", sector: "Chemicals" },
  { name: "Tata Chemicals", ticker: "TATACHEM.NS", sector: "Chemicals" },
  { name: "GMR Airports", ticker: "GMRINFRA.NS", sector: "Infrastructure" },
  { name: "IRB Infrastructure", ticker: "IRB.NS", sector: "Infrastructure" },
  { name: "NCC Ltd", ticker: "NCC.NS", sector: "Infrastructure" },
  { name: "KNR Constructions", ticker: "KNRCON.NS", sector: "Infrastructure" },
  { name: "Ahluwalia Contracts", ticker: "AHLUCONT.NS", sector: "Infrastructure" },
  { name: "NBCC India", ticker: "NBCC.NS", sector: "Infrastructure" },
  { name: "Sail (Steel Authority)", ticker: "SAIL.NS", sector: "Metals" },
  { name: "NMDC", ticker: "NMDC.NS", sector: "Metals" },
  { name: "Vedanta", ticker: "VEDL.NS", sector: "Metals" },
  { name: "National Aluminium", ticker: "NATIONALUM.NS", sector: "Metals" },
  { name: "Hindustan Zinc", ticker: "HINDZINC.NS", sector: "Metals" },
  { name: "Jindal Steel & Power", ticker: "JINDALSTEL.NS", sector: "Metals" },
  { name: "Ratnamani Metals", ticker: "RATNAMANI.NS", sector: "Metals" },
  { name: "Manappuram Finance", ticker: "MANAPPURAM.NS", sector: "NBFC" },
  { name: "Bajaj Holdings", ticker: "BAJAJHLDNG.NS", sector: "NBFC" },
  { name: "L&T Finance", ticker: "LTFH.NS", sector: "NBFC" },
  { name: "Poonawalla Fincorp", ticker: "POONAWALLA.NS", sector: "NBFC" },
  { name: "HDFC AMC", ticker: "HDFCAMC.NS", sector: "NBFC" },
  { name: "UTI AMC", ticker: "UTIAMC.NS", sector: "NBFC" },
  { name: "Angel One", ticker: "ANGELONE.NS", sector: "NBFC" },
  { name: "BSE Ltd", ticker: "BSE.NS", sector: "NBFC" },
  { name: "MCX India", ticker: "MCX.NS", sector: "NBFC" },
  { name: "General Insurance Corp", ticker: "GICRE.NS", sector: "Insurance" },
  { name: "New India Assurance", ticker: "NIACL.NS", sector: "Insurance" },
  { name: "Star Health Insurance", ticker: "STARHEALTH.NS", sector: "Insurance" },
  { name: "Garden Reach Shipbuilders", ticker: "GRSE.NS", sector: "Defense" },
  { name: "BDL (Bharat Dynamics)", ticker: "BDL.NS", sector: "Defense" },
  { name: "Paras Defence", ticker: "PARAS.NS", sector: "Defense" },
  { name: "Zen Technologies", ticker: "ZENTEC.NS", sector: "Defense" },
  { name: "Rail Vikas Nigam (RVNL)", ticker: "RVNL.NS", sector: "Railways" },
  { name: "Jupiter Wagons", ticker: "JWL.NS", sector: "Railways" },
  { name: "Titagarh Rail Systems", ticker: "TITAGARH.NS", sector: "Railways" },
  { name: "Texmaco Rail", ticker: "TEXRAIL.NS", sector: "Railways" },
  { name: "Campus Activewear", ticker: "CAMPUS.NS", sector: "Consumer" },
  { name: "Metro Brands", ticker: "METROBRAND.NS", sector: "Consumer" },
  { name: "Sapphire Foods (KFC/PH)", ticker: "SAPPHIRE.NS", sector: "Consumer" },
  { name: "Devyani International", ticker: "DEVYANI.NS", sector: "Consumer" },
  { name: "Restaurant Brands Asia", ticker: "RBA.NS", sector: "Consumer" },
  { name: "Honasa Consumer (Mamaearth)", ticker: "HONASA.NS", sector: "Consumer" },
  { name: "Go Digit Insurance", ticker: "GODIGIT.NS", sector: "Insurance" },
  { name: "Kaynes Technology", ticker: "KAYNES.NS", sector: "Electronics" },
  { name: "Syrma SGS Technology", ticker: "SYRMA.NS", sector: "Electronics" },
  { name: "Amber Enterprises", ticker: "AMBER.NS", sector: "Electronics" },
  { name: "Waaree Energies", ticker: "WAAREEENER.NS", sector: "Renewable Energy" },
  { name: "Premier Energies", ticker: "PREMIERENE.NS", sector: "Renewable Energy" },
  { name: "Websol Energy", ticker: "WEBSOLENER.NS", sector: "Renewable Energy" },
  { name: "Swiggy", ticker: "SWIGGY.NS", sector: "Tech" },
  { name: "Firstcry (Brainbees)", ticker: "FIRSTCRY.NS", sector: "Tech" },
  { name: "Ola Electric", ticker: "OLAELEC.NS", sector: "Tech" },
  { name: "Hyundai Motor India", ticker: "HYUNDAI.NS", sector: "Auto" },
  { name: "Afcons Infrastructure", ticker: "AFCONS.NS", sector: "Infrastructure" },
];

export function searchStocks(query: string, limit = 8): StockEntry[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase().trim();
  const results: { stock: StockEntry; score: number }[] = [];

  for (const stock of NSE_STOCKS) {
    const name = stock.name.toLowerCase();
    const ticker = stock.ticker.toLowerCase().replace(".ns", "");
    const sector = stock.sector.toLowerCase();

    let score = 0;
    if (name === q || ticker === q) score = 100;
    else if (name.startsWith(q)) score = 80;
    else if (ticker.startsWith(q)) score = 75;
    else if (name.includes(q)) score = 50;
    else if (ticker.includes(q)) score = 45;
    else if (sector.includes(q)) score = 20;
    else {
      const words = q.split(/\s+/);
      const matched = words.filter(w => name.includes(w) || ticker.includes(w));
      if (matched.length > 0) score = 10 + matched.length * 10;
    }

    if (score > 0) results.push({ stock, score });
  }

  return results
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(r => r.stock);
}
