import type { Metadata } from "next";
import { LegalPage, H2 } from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service — White Tiger",
  description: "Terms governing use of the White Tiger financial intelligence platform.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="May 29, 2026">
      <p>
        Welcome to White Tiger. By accessing or using this platform, you agree to these Terms
        of Service. Please read them carefully. If you do not agree, do not use the platform.
      </p>

      <H2>1. Nature of the Service</H2>
      <p>
        White Tiger is an AI-powered research and educational tool covering equities, mutual
        funds, crypto, forex, commodities, bonds, derivatives, and real estate. All analysis,
        scores, target prices, fair values, and verdicts are generated by automated models and
        third-party data feeds. They are provided for informational and educational purposes only.
      </p>

      <H2>2. Not Financial Advice</H2>
      <p>
        White Tiger is <strong>not</strong> a SEBI-registered investment adviser, research analyst,
        stockbroker, or portfolio manager. Nothing on this platform constitutes financial,
        investment, legal, accounting, or tax advice, nor a solicitation or recommendation to buy
        or sell any security or instrument. Always consult a SEBI-registered investment adviser
        before making any financial decision.
      </p>

      <H2>3. Data Accuracy & Sources</H2>
      <p>
        Data is aggregated from public and third-party sources (including NSE/BSE, AMFI, exchanges,
        and market-data providers) and may be delayed, incomplete, estimated, or inaccurate. Some
        figures are static estimates or AI-generated and are labelled where practical. You are
        responsible for verifying any data independently before relying on it.
      </p>

      <H2>4. No Warranty</H2>
      <p>
        The platform is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind,
        whether express or implied, including accuracy, fitness for a particular purpose, or
        uninterrupted availability.
      </p>

      <H2>5. Limitation of Liability</H2>
      <p>
        To the maximum extent permitted by law, White Tiger and its operator shall not be liable
        for any direct, indirect, incidental, or consequential losses (including trading or
        investment losses) arising from use of, or reliance on, the platform.
      </p>

      <H2>6. Acceptable Use</H2>
      <p>
        You agree not to scrape, resell, reverse-engineer, or misuse the platform, nor to use it
        for any unlawful purpose. Paid plans are subject to the limits shown at purchase.
      </p>

      <H2>7. Changes</H2>
      <p>
        These terms may be updated from time to time. Continued use after changes constitutes
        acceptance of the revised terms.
      </p>

      <H2>8. Contact</H2>
      <p>
        Questions about these terms can be sent to the contact address listed on the About page.
      </p>
    </LegalPage>
  );
}
